baseurl: 'https://cs.calvin.edu/courses/cs/344/23sp/'
languageCode: "en-us"
title: "CS 344 Spring 2023 at Calvin University"
theme: "hugo-xmin"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
footnotereturnlinkcontents: "↩"
relativeURLs: true
canonifyURLs: true

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Syllabus
      url: "/syllabus"
      weight: 2
    - name: Units
      url: "/units"
      weight: 4
    - name: "Outline"
      url: "/outline"
      weight: 5
    - name: Discussions
      url: "/discussions/"
      weight: 6
    - name: Project
      url: "/project"
      weight: 7
    - name: Resources
      url: "/resources"
      weight: 8

params:
  description: ""
  footer: "&copy; [Ken Arnold](https://kenarnold.org) 2021 -- {Year}"

markup:
  highlight:
    codeFences: true
  goldmark:
    renderer:
      unsafe: true
