---
title: Reflection 4
author: Ken Arnold
date: '2021-03-08'
slug: reflection-4
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2021-03-08'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

*This assignment should be turned in on Moodle.*

This reflection is a bit different from previous ones: it's systematic and objective. Consider it a check-in of what you have achieved in the first third (approximately) of the semester.

### Technology

Complete the following:

-   Chapter 1: \_\_%

    -   Active Reading: \_\_%

    -   Reading Quiz 1: \_\_%

-   Chapter 2: \_\_%

    -   Active Reading: \_\_%

    -   Reading Quiz 2: \_\_%

-   Chapter 4: \_\_%

    -   Active Reading: \_\_%

    -   Reading Quiz 4: \_\_%

-   Check-in Quiz 2

-   Check-in Quiz 4

-   Homework 1

-   Portfolio Foundations section: \_\_%

Compute a grade for yourself based on the simple average of your scores for each activity. (You may use a different weighting if you make a good argument.) Specific instructions for each

Quizzes

For each of the following quizzes, please review the quiz and the feedback.

### Community

There are many different good ways to contribute to others' learning about AI (inside or outside this class), so I do not expect everyone to have done each of the following.

-   What Piazza post or reply do you want to highlight and why? Include the URL. (If you posted anonymously and want to remain anonymous, just say "posted anonymously" or "replied anonymously").

-   What was a specific way that you helped a fellow student in lab/class/homework, or were helped by them?

-   What discussion post do you want to highlight as an example of making another student feel heard or valued? Include a URL.

-   Beyond these, what else have you done to contribute to others' learning about AI since our class started? Please be specific.

Compute a grade for each of these four areas, then compute an overall grade as `min(100, sum(grades) * 100 / 20)`.

### Context / History

**Reading Quiz 3**

Discussion forums or class discussions:

-   What *initial post* do you want to highlight and why? Include the URL.

-   What *response post* do you want to highlight and why?

-   What's something you'll want to remember from a non-technical *class discussion* and why?

-   What's something you'll want to remember from something non-technical you *read* for this class (in our book, an assigned non-technical reading, or otherwise) and why?

Compute a grade as follows:

-   Grade each of the four areas above out of 10 points.

-   Compute min(100, sum(grades) \* 100 / 30)

**Overall feedback?**

Optional, but it would be helpful to share how you feel like things are going this week. Your input will be helpful especially to help me make some decisions about our pace (when do we move on to ch4?), and I want to make sure our organization / structure is clear.
